before_script:
    - module load nucleisys/riscv-nuclei-elf-gcc
    - module load nucleisys/openocd
    - source .ci/build_sdk.sh
    - source .ci/build_applications.sh

stages:
    - doc_build
    - doc_deploy
    - build_hbird_eval
    - build_hbird_ddr_200t

## Job for build document
build_doc:
    stage: doc_build
    only:
        changes:
          - doc/source/**/**/**/*
    retry: 1
    artifacts:
        name: "hbird_sdk_doc-${CI_COMMIT_SHA::8}"
        paths:
            - doc/build
        expire_in: 2 day
    script:
        - cd doc
        - pip3 install --user -r requirements.txt
        - export PATH=$HOME/.local/bin:$PATH
        - make clean
        - make all
        - make latexpdf
        - make clean_xml
        - cp build/latex/*.pdf build/html/
    tags:
        - software-server

## Job for deploy document to internal server
deploy_doc:
    stage: doc_deploy
    when: on_success
    retry: 1
    only:
        refs:
          - master
        changes:
          - doc/source/**/**/**/*
    script:
        - ssh xl01 "rm -rf /home/xl_ci/doc_center/hbird_sdk/*"
        - ssh xl01 "mkdir -p /home/xl_ci/doc_center/hbird_sdk/"
        - cd doc/build
        - scp -r html xl01:/home/xl_ci/doc_center/hbird_sdk
    tags:
        - software-server
    dependencies:
        - build_doc

## Job for deploy document to nuclei website
deploy_website:
    stage: doc_deploy
    when: on_success
    retry: 1
    only:
        refs:
          - master
        changes:
          - doc/source/**/**/**/*
    script:
        - ./.ci/ftp_deploy.sh $FTPUSER $FTPPWD $FTPSERVER doc/build/html hbird_sdk
    tags:
        - software-server
    dependencies:
        - build_doc

## Jobs for board hbird_eval
.build_hbird_eval_job_template: &build_hbird_eval_job_def
    stage: build_hbird_eval
    script:
        - SOC=hbird BOARD=hbird_eval hsdk_build_directory    application
        - SOC=hbird BOARD=hbird_eval hsdk_build_directory    test

# Build For HBird Evaluation Board with E203 Core, with Flash, FlashXIP, ILM Mode
build_hbird_eval_ilm_e203:
    variables:
        DOWNLOAD: "ilm"
        SOC: "hbird"
        CORE: "e203"
    <<: *build_hbird_eval_job_def

build_hbird_eval_flash_e203:
    variables:
        DOWNLOAD: "flash"
        CORE: "e203"
    <<: *build_hbird_eval_job_def

build_hbird_eval_flashxip_e203:
    variables:
        DOWNLOAD: "flashxip"
        CORE: "e203"
    <<: *build_hbird_eval_job_def

# Build For E205F, with Flash, FlashXIP, ILM Mode
build_hbird_eval_ilm_e205f:
    variables:
        DOWNLOAD: "ilm"
        CORE: "e205f"
        FIND_IGNORE: "! -wholename \"*dsp*\""
    <<: *build_hbird_eval_job_def

build_hbird_eval_flash_e205f:
    variables:
        DOWNLOAD: "flash"
        CORE: "e205f"
        FIND_IGNORE: "! -wholename \"*dsp*\""
    <<: *build_hbird_eval_job_def

build_hbird_eval_flashxip_e205f:
    variables:
        DOWNLOAD: "flashxip"
        CORE: "e205f"
        FIND_IGNORE: "! -wholename \"*dsp*\""
    <<: *build_hbird_eval_job_def

# Build For E201E, with Flash, FlashXIP, ILM Mode
build_hbird_eval_ilm_e201e:
    variables:
        DOWNLOAD: "ilm"
        CORE: "e201e"
        FIND_IGNORE: "! -wholename \"*dsp*\""
    <<: *build_hbird_eval_job_def

build_hbird_eval_flash_e201e:
    variables:
        DOWNLOAD: "flash"
        CORE: "e201e"
        FIND_IGNORE: "! -wholename \"*dsp*\""
    <<: *build_hbird_eval_job_def

build_hbird_eval_flashxip_e201e:
    variables:
        DOWNLOAD: "flashxip"
        CORE: "e201e"
        FIND_IGNORE: "! -wholename \"*dsp*\""
    <<: *build_hbird_eval_job_def

# Build For E201, with Flash, FlashXIP, ILM Mode
build_hbird_eval_ilm_e201:
    variables:
        DOWNLOAD: "ilm"
        CORE: "e201"
        FIND_IGNORE: "! -wholename \"*dsp*\""
    <<: *build_hbird_eval_job_def

build_hbird_eval_flash_e201:
    variables:
        DOWNLOAD: "flash"
        CORE: "e201"
        FIND_IGNORE: "! -wholename \"*dsp*\""
    <<: *build_hbird_eval_job_def

build_hbird_eval_flashxip_e201:
    variables:
        DOWNLOAD: "flashxip"
        CORE: "e201"
        FIND_IGNORE: "! -wholename \"*dsp*\""
    <<: *build_hbird_eval_job_def

## Jobs for board hbird_ddr_200t
.build_hbird_ddr_200t_job_template: &build_hbird_ddr_200t_job_def
    stage: build_hbird_ddr_200t
    script:
        - SOC=hbirdv2 BOARD=hbird_ddr_200t hsdk_build_directory    application
        - SOC=hbirdv2 BOARD=hbird_ddr_200t hsdk_build_directory    test

# Build For HBird Evaluation Board with E203 Core, with Flash, FlashXIP, ILM Mode
build_hbird_ddr_200t_ilm_e203:
    variables:
        DOWNLOAD: "ilm"
        CORE: "e203"
    <<: *build_hbird_ddr_200t_job_def

build_hbird_ddr_200t_flash_e203:
    variables:
        DOWNLOAD: "flash"
        CORE: "e203"
    <<: *build_hbird_ddr_200t_job_def

build_hbird_ddr_200t_flashxip_e203:
    variables:
        DOWNLOAD: "flashxip"
        CORE: "e203"
    <<: *build_hbird_ddr_200t_job_def

# Build For E205F, with Flash, FlashXIP, ILM Mode
build_hbird_ddr_200t_ilm_e205f:
    variables:
        DOWNLOAD: "ilm"
        CORE: "e205f"
        FIND_IGNORE: "! -wholename \"*dsp*\""
    <<: *build_hbird_ddr_200t_job_def

build_hbird_ddr_200t_flash_e205f:
    variables:
        DOWNLOAD: "flash"
        CORE: "e205f"
        FIND_IGNORE: "! -wholename \"*dsp*\""
    <<: *build_hbird_ddr_200t_job_def

build_hbird_ddr_200t_flashxip_e205f:
    variables:
        DOWNLOAD: "flashxip"
        CORE: "e205f"
        FIND_IGNORE: "! -wholename \"*dsp*\""
    <<: *build_hbird_ddr_200t_job_def

# Build For E201E, with Flash, FlashXIP, ILM Mode
build_hbird_ddr_200t_ilm_e201e:
    variables:
        DOWNLOAD: "ilm"
        CORE: "e201e"
        FIND_IGNORE: "! -wholename \"*dsp*\""
    <<: *build_hbird_ddr_200t_job_def

build_hbird_ddr_200t_flash_e201e:
    variables:
        DOWNLOAD: "flash"
        CORE: "e201e"
        FIND_IGNORE: "! -wholename \"*dsp*\""
    <<: *build_hbird_ddr_200t_job_def

build_hbird_ddr_200t_flashxip_e201e:
    variables:
        DOWNLOAD: "flashxip"
        CORE: "e201e"
        FIND_IGNORE: "! -wholename \"*dsp*\""
    <<: *build_hbird_ddr_200t_job_def

# Build For E201, with Flash, FlashXIP, ILM Mode
build_hbird_ddr_200t_ilm_e201:
    variables:
        DOWNLOAD: "ilm"
        CORE: "e201"
        FIND_IGNORE: "! -wholename \"*dsp*\""
    <<: *build_hbird_ddr_200t_job_def

build_hbird_ddr_200t_flash_e201:
    variables:
        DOWNLOAD: "flash"
        CORE: "e201"
        FIND_IGNORE: "! -wholename \"*dsp*\""
    <<: *build_hbird_ddr_200t_job_def

build_hbird_ddr_200t_flashxip_e201:
    variables:
        DOWNLOAD: "flashxip"
        CORE: "e201"
        FIND_IGNORE: "! -wholename \"*dsp*\""
    <<: *build_hbird_ddr_200t_job_def
